{% set name = "fenics-pulse" %}
{% set version = "2023.0.0" %}

package:
  name: pulse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d120dd62b0f094956abecbc5e4fdeeb9f75b8ffc14fdf9d653f0bd25696376b3

build:
  number: 0
  skip: true
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - h5py
    - fenics
    - scipy
    - numpy
    - daiquiri
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
