{% set name = "fenics-pulse" %}
{% set version = "2023.2.0" %}


package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: b2fc976cfdc0c09089f06a4a0f0de44ee8d3fcd73c57411756c52ace62fb360e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - fenics
    - scipy
    - numpy
    - daiquiri
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
