{% set name = "fenics-pulse" %}
{% set version = "2024.0.1" %}


package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: fe7ce6298638443d8e22a1afe8a63308f07bd61351466e4205dd3c12f82e1985

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py
    - fenics
    - scipy
    - numpy
    - daiquiri
test:
  requires:
    - python {{ python_min }}
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
