{% set version = "2020.1" %}

package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: ac640623adc871fe75d64d771467ec09af9be3ef31a67173b5445259c1097441

build:
  number: 0
  skip: true  # [win or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python

    - pip
    - h5py
    - fenics
    - scipy
    - matplotlib-base
  run:
    - python
    - h5py
    - fenics
    - scipy
    - matplotlib-base
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse/html/index.html
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse/html/index.html
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
