{% set version = "2022.1.3" %}

package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: 6a217b7b50da326bf893e2047ee987182ffec5cc23d6edf251847efe10196900

build:
  number: 0
  skip: true
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - fenics
    - scipy
    - numpy
    - daiquiri
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
