{% set version = "2021.0.1" %}

package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: ce1d5a74d660d3f22cf6dc3f7a40e4e7944ca0fafe4e347945759fad163075be

build:
  number: 0
  skip: true  # [win or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - fenics
  run:
    - python
    - h5py
    - fenics
    - scipy
    - numpy
    - daiquiri
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse/html/index.html
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse/html/index.html
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
