{% set version = "2020.2" %}

package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: 1d5025ac444a2737e4079217713978c10083566d7e11c4daea62003d9bcf4a0e

build:
  number: 1
  skip: true  # [win or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python

    - pip
    - h5py
    - fenics
    - scipy
    - matplotlib-base
  run:
    - python
    - h5py
    - fenics
    - scipy
    - matplotlib-base
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse/html/index.html
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse/html/index.html
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
