travis:
  secure:
    BINSTAR_TOKEN: toHlciCSBQC5GB7CDVM8NRs6wb9ECpY6joqY6NjdBrH8K2td45kiimGxSaOK3ZHAk2p82oqvnvyHoWBU5E8M+QhFZDX9C7zSTisJoMfrtrCav9E4qDKEU3JXCP09C1aklf3p9dPLqBnq/LDnrswSsL71LgyffBBn7WuIUMaU3dsNhCbXsVNP5bVQsqvmfdFaFVN4K3gYzhAqZcQSnTrgGbBTRUfA4HwLRH0jn7zgWruQF+zwG3+pP1GYfrBXKK+Tu61vBHI4BEczvla+eESrWUJQi+xsfhEadMBrWbKklsuquHeFGEDDM+1DODVWB5pQZaGcwLpLxVaCOJOgBsho2tCoMzVQsnixF6GT4BzV7dN8QZSPxvOfDC++L1drWEdJq8lDG8aekDr5M2TFSlQQxFlDM8gQn+rBi+6/FEuKejBmxF6cbSgXRH20MnWr1oyjDsCbbVDmwhdE94gBojRYI9rYCEqkfnpjwTbfZp6ZZn7yscg3s9khLksL7kXHvQ9qQw3baCbDE2Z35QFL8tFlLhF2tgpHhNgkUPw2iN1ZYfNSNc2VvhCL5Okb18xmOb9dLs4FJI63UBvMPouSEV/BHwhnStDNKHnueqYQ28+N3osnkr9ltbHTXuNKG9edUBI8pvRbCPED/sBxXeaD4EIN2w8N+vACF1hYugGWY5LdPos=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
